version: "3.4"

services:
  mysql:
    image: mysql:8.0.31
    container_name: "data-pipeline-00-mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "0"
      MYSQL_DATABASE: "development"
    volumes:
      - ./rdb/mysql/init:/docker-entrypoint-initdb.d
      - ./rdb/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks: 
      - network-data-pipeline
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          memory: 2G

  postgres:
    image: postgres:12.4-alpine
    container_name: "data-pipeline-00-postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    networks:
      - network-data-pipeline
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          memory: 2G

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "data-pipeline-00-pgadmin"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jianliu0616@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - network-data-pipeline
    depends_on:
      - postgres

networks:
    network-data-pipeline:
      driver: bridge
